### ISSUE TITLE
fix: next/head가 적용되지 않는 이슈

### ISSUE THREAD

**Issue by yuriver** [kagrin97/NextJS-myblog#27]
안녕하세요, 흥미로운 repo여서 관심있게 봤습니다.
[초기 html에 서버에서 동적으로 생성된 메타태그가 주입되지 않는 문제](https://github.com/kagrin97/NextJS-myblog#4-%ED%92%80%EB%A6%AC%EC%A7%80-%EC%95%8A%EB%8A%94-%ED%8A%B8%EB%9F%AC%EB%B8%94)라는 내용을 봤는데, `_app.tsx`에서 SSR일 때 비어있는 dom을 렌더하게 되어 원하시는 메타데이터가 주입이 되지 않는것을 발견했습니다. 해당 부분을 개선하시면 원하시는 메타데이터가 적용되실거에요.

https://github.com/kagrin97/NextJS-myblog/blob/baab7edbffdd482865ed8ace67500f2edac00489/pages/_app.tsx#L10-L20

**Comment by kagrin97** [comment]
오 해당 부분을 삭제하고 window, documents를 사용하는 로직을 mount시에만
동작하도록 변경했더니 메타데이터가 잘 적용이 되네요! 감사합니다
